---
pipeline: Scope1_YokogawaUS_run1
output_dir: profiles
platemap_well_column: Metadata_well_position
compartments:
  - cells
  - cytoplasm
  - nuclei
aggregate:
  perform: false
  plate_column: Metadata_Plate
  well_column: Metadata_Well
  method: median
  fields: all
  image_feature_categories:
    - Count
    - Intensity
annotate:
  perform: true
  well_column: Metadata_Well
  external :
    perform: true
    file: JUMP-Target-1_compound_metadata.tsv
    merge_column: broad_sample
normalize:
  perform: true
  method: mad_robustize
  features: infer
  mad_robustize_fudge_factor: 0
  image_features: false
normalize_negcon:
  perform: true
  method: mad_robustize
  features: infer
  mad_robustize_fudge_factor: 0
  image_features: false
feature_select:
  perform: true
  features: infer
  level: batch
  gct: true
  image_features: false
  operations:
    - variance_threshold
    - correlation_threshold
    - drop_na_columns
    - blocklist
feature_select_negcon:
  perform: true
  features: infer
  level: batch
  gct: true
  image_features: false
  operations:
    - variance_threshold
    - correlation_threshold
    - drop_na_columns
    - blocklist
quality_control:
  perform: true
  summary:
    perform: false
    row: Metadata_Row
    column: Metadata_Col
  heatmap:
    perform : true
options:
  compression: gzip
  float_format: "%.5g"
  samples: all
---
batch: 2020_11_16_Scope1_YokogawaUS
plates:
  - name: BRO0117014_10x
    process: true
  - name: BRO0117033_20x
    process: true
  - name: BRO0117033_20xb     
    process: true
  - name: BRO0117056_20x    
    process: true
  - name: BRO0117056_20xb     
    process: true
  - name: BRO0117059_20X
    process: true
  - name: BRO0117059_40x
    process: true
  - name: BRO01177034_20x 
    process: true
process: true

