---
pipeline: Scope1_MolDev_10X_4siteZ_run1
output_dir: profiles
platemap_well_column: Metadata_well_position
compartments:
  - cells
  - cytoplasm
  - nuclei
aggregate:
  perform: false
  plate_column: Metadata_Plate
  well_column: Metadata_Well
  method: median
  fields: all
  image_feature_categories:
    - Count
    - Intensity
annotate:
  perform: false
  well_column: Metadata_Well
  external :
    perform: true
    file: JUMP-MOA_compound_metadata.tsv
    merge_column: broad_sample
normalize:
  perform: false
  method: mad_robustize
  features: infer
  mad_robustize_fudge_factor: 0
  image_features: false
normalize_negcon:
  perform: false
  method: mad_robustize
  features: infer
  mad_robustize_fudge_factor: 0
  image_features: false
feature_select:
  perform: true
  features: infer
  level: plate
  gct: true
  image_features: false
  operations:
    - variance_threshold
    - correlation_threshold
    - drop_na_columns
    - blocklist
feature_select_negcon:
  perform: true
  features: infer
  level: plate
  gct: true
  image_features: false
  operations:
    - variance_threshold
    - correlation_threshold
    - drop_na_columns
    - blocklist
quality_control:
  perform: true
  summary:
    perform: false
    row: Metadata_Row
    column: Metadata_Col
  heatmap:
    perform : true
options:
  compression: gzip
  float_format: "%.5g"
  samples: all
---
batch: Scope1_MolDev_10X_4siteZ
plates:
  - name: Plate3_PCO_6ch_4site_10XPA_Crestz 
    process: true
process: true

